### ISSUE TITLE
Fails silently if it cannot find Git

### ISSUE THREAD

**Issue by dracan** [Readify/GitViz#11]
If Git.exe cannot be found, then it fails silently rather than showing a message saying why. Makes it appear that it's just not working. I had to run it in the debugger to find out why it wasn't working. It's the Process.Start that throws an exception, which then gets swallowed by the ViewModel. I'm happy to do a PR with a simple messagebox if you want. Depends how you want errors handled / displayed. I have limited WPF knowledge - so a messagebox probably isn't the best way to do this?

**Comment by dracan** [comment]
Ps. Great app though! :) Want to use it for a couple of diagrams in a blogpost. Hope that's okay :)

**Comment by tathamoddie** [comment]
Thanks for the report @dracan. I'm not fussed by a simple message box; no need to overcomplicate it. (The fact that we use `git.exe` instead of `libgit2sharp` is the biggest hack job of them all anyway.)

A PR would be great.
